# Generated by Django 3.2.4 on 2021-10-30 12:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0003_auto_20211030_1732'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=11, verbose_name='invoice number')),
                ('payment_method', models.CharField(choices=[('manual', 'manual transfer bank'), ('online', 'online')], max_length=10, verbose_name='payment method')),
                ('payment_proof', models.ImageField(blank=True, null=True, upload_to='images', verbose_name='proof of payment')),
                ('payment_token', models.CharField(blank=True, max_length=255, null=True, verbose_name='payment token')),
                ('shipping_courier', models.CharField(choices=[('jne', 'JNE'), ('tiki', 'Tiki'), ('pos_indonesia', 'Pos Indonesia')], max_length=20, verbose_name='shipping courier')),
                ('shipping_service', models.CharField(max_length=100, verbose_name='shipping service')),
                ('shipping_tracking_number', models.CharField(blank=True, max_length=255, null=True, verbose_name='tracking number')),
                ('customer_name', models.CharField(max_length=100, verbose_name='customer name')),
                ('customer_phone', models.CharField(max_length=20, verbose_name='customer phone')),
                ('customer_address', models.TextField(verbose_name='customer address')),
                ('customer_postal_code', models.CharField(blank=True, max_length=5, null=True, verbose_name='customer postal code')),
                ('purchased_at', models.DateTimeField(blank=True, null=True, verbose_name='Purchased date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('status', models.IntegerField(choices=[(0, 'pending'), (1, 'paid'), (2, 'shipped'), (3, 'completed'), (4, 'canceled')], default=0, verbose_name='status')),
                ('sub_total', models.FloatField(verbose_name='sub total')),
                ('total_shipping', models.FloatField(verbose_name='shipping rate')),
                ('total', models.FloatField(verbose_name='total')),
                ('customer_city', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.city', verbose_name='customer city')),
                ('customer_state', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.state', verbose_name='customer state')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'order',
                'verbose_name_plural': 'orders',
                'db_table': 'orders',
                'ordering': ('created_at',),
            },
        ),
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['created_at'], 'verbose_name': 'produk', 'verbose_name_plural': 'produk'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='deskripsi'),
        ),
        migrations.AlterField(
            model_name='product',
            name='image',
            field=models.ImageField(upload_to='images', verbose_name='gambar'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=models.FloatField(verbose_name='harga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.IntegerField(verbose_name='stok'),
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.FloatField(verbose_name='berat'),
        ),
        migrations.CreateModel(
            name='OrderProduct',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('weight', models.FloatField(verbose_name='berat')),
                ('price', models.FloatField(verbose_name='harga')),
                ('total', models.FloatField(verbose_name='total')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='order')),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='produk')),
            ],
            options={
                'db_table': 'order_products',
                'ordering': ['id'],
            },
        ),
    ]
