# Generated by Django 3.2.4 on 2021-10-30 14:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('store', '0004_auto_20211030_1906'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'ordering': ('created_at',), 'verbose_name': 'pesanan', 'verbose_name_plural': 'pesanan'},
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_name',
            field=models.CharField(max_length=100, verbose_name='nama pelanggan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='customer_phone',
            field=models.CharField(max_length=20, verbose_name='no.telp/hp pelanggan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='invoice_number',
            field=models.CharField(max_length=11, verbose_name='nomor pesanan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('manual', 'transfer bank'), ('online', 'online banking')], max_length=10, verbose_name='metode pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_proof',
            field=models.ImageField(blank=True, null=True, upload_to='images', verbose_name='bukti pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='payment_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='token pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_courier',
            field=models.CharField(choices=[('jne', 'JNE'), ('tiki', 'Tiki'), ('pos_indonesia', 'Pos Indonesia')], max_length=20, verbose_name='kurir'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_service',
            field=models.CharField(max_length=100, verbose_name='layanan'),
        ),
        migrations.AlterField(
            model_name='order',
            name='shipping_tracking_number',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='nomor resi'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.IntegerField(choices=[(0, 'belum dibayar'), (1, 'sudah dibayar'), (2, 'sudah dikirim'), (3, 'selesai'), (4, 'sudah dibatalkan')], default=0, verbose_name='status'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.order', verbose_name='pesanan'),
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(verbose_name='quantity')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.product', verbose_name='produk')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'cart',
                'db_table': 'carts',
                'ordering': ('created_at',),
            },
        ),
    ]
