# Generated by Django 3.2.4 on 2021-10-31 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_auto_20211030_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cart',
            options={'ordering': ('created_at',), 'verbose_name': 'keranjang'},
        ),
        migrations.AlterField(
            model_name='cart',
            name='quantity',
            field=models.IntegerField(verbose_name='jumlah'),
        ),
        migrations.AlterField(
            model_name='order',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='tanggal pembayaran'),
        ),
        migrations.AlterField(
            model_name='order',
            name='total_shipping',
            field=models.FloatField(verbose_name='biaya pengiriman'),
        ),
        migrations.AlterField(
            model_name='orderproduct',
            name='quantity',
            field=models.IntegerField(verbose_name='jumlah'),
        ),
    ]
